name: plasmapy-test-helpers

channels:
  - astropy
  - conda-forge

dependencies:
  - python>=3.7
  - numpy
  - astropy
  - pillow
  - pip
  - pip:
    - numba-scipy
    - hypothesis
    - docutils < 0.17
    - numpydoc
    - pytest
    - pygments>=2.4.1
    - sphinx>=3.2.0
    - sphinx-gallery
    - sphinx_rtd_theme
    - towncrier >= 19.2.0
    - pytest-regressions
    - notebook
